### ISSUE TITLE
Fix handling of $schema on body extraction

### ISSUE THREAD

**Issue by aldemirenes** [snowplow-incubator/iglu-scala-core#24]
[Original ticket](https://github.com/snowplow/iglu/issues/165)

**Comment by chuwy** [comment]
Prioritizing for 1.0.0.

Out new JSON Schema validator is much more restrictive about meta schema and software must be very explicit that it is required. Hence, I think we need to make following changes:
1. `SelfDescribinSchema.parse` should return error if there's no valid `$schema` error
2. `schema` should not include it
3. `normalize` must add it back
